version: "1.0"

services:
  app:
    container_name: cart-microservice
    command: java -jar target/warehouse-service-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - database-cart
    volumes:
      - ./:/app/app
    links:
      - database-cart
    networks:
      - internal

  database-cart:
    image: postgres
    container_name: database-cart
    ports:
      - "5433:5433"
    volumes:
      - ./:/app/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cart_db
    networks:
      - internal

networks:
  internal:
    name: internal