version: "1.0"

services:
  app:
    container_name: cart-microservice
    command: java -jar target/cart-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - database-cart
    volumes:
      - ./:/app/app
    links:
      - database-cart
    networks:
      - internal
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672

  database-cart:
    image: postgres
    container_name: database-cart
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./:/app/
    command: -p 5433
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cart_db
    networks:
      - internal

networks:
  internal:
    name: internal