server:
  port: 9002

spring:
  application:
    name: CART-SERVICE

  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create
    show-sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cart_db
    username: postgres
    password: postgres

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server
