server:
  port: 9002

spring:
  application:
    name: CART-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost